version: "3"

services:
  hello:
    build: .
    command: ./server_bye.py
    volumes:
     - ./:/app
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
